# -*- coding: utf-8 -*-
"""ATM_Interface

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KO1TJ8KdzRm4HX4vQQELcGP7WJ-se_sY
"""

# ATM Interface - Full Program

# Step 1: PIN Verification
correct_pin = "1432"  # Set your PIN here
attempts = 3

while attempts > 0:
    entered_pin = input("Enter your 4-digit ATM PIN: ")
    if entered_pin == correct_pin:
        print("PIN Verified Successfully!\n")
        break
    else:
        attempts -= 1
        print(f"Incorrect PIN! Attempts left: {attempts}")

if attempts == 0:
    print("Too many wrong attempts. Card blocked!")
    exit()  # Exit the program if PIN attempts are over

# Step 2: ATM Operations

# Initial balance
balance = 1000  # You can change the starting balance

def atm_menu():
    print("\n----- Welcome to the ATM -----")
    print("1. Check Balance")
    print("2. Deposit Money")
    print("3. Withdraw Money")
    print("4. Exit")

while True:
    atm_menu()
    try:
        choice = int(input("Please select an option (1-4): "))
    except ValueError:
        print("Invalid input! Please enter a number between 1-4.")
        continue

    if choice == 1:
        print(f"Your current balance is: ₹{balance}")

    elif choice == 2:
        try:
            deposit_amount = float(input("Enter amount to deposit: ₹"))
            if deposit_amount <= 0:
                print("Deposit amount must be positive!")
                continue
            balance += deposit_amount
            print(f"₹{deposit_amount} deposited successfully.")
            print(f"Updated balance: ₹{balance}")
        except ValueError:
            print("Invalid amount entered!")

    elif choice == 3:
        try:
            withdraw_amount = float(input("Enter amount to withdraw: ₹"))
            if withdraw_amount <= 0:
                print("Withdraw amount must be positive!")
                continue
            if withdraw_amount > balance:
                print("Insufficient balance!")
            else:
                balance -= withdraw_amount
                print(f"₹{withdraw_amount} withdrawn successfully.")
                print(f"Updated balance: ₹{balance}")
        except ValueError:
            print("Invalid amount entered!")

    elif choice == 4:
        print("Thank you for using the ATM. Goodbye!")
        break

    else:
        print("Invalid option! Please choose between 1 and 4.")